//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/InputSystem/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""PControl"",
            ""id"": ""d8e5fe9e-e93b-4423-9188-5cbf1841f69a"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""07503baf-7f2c-4307-adef-0e65e80a538e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""2038832e-1173-43c7-a637-1bd3d4f71534"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""49775ed6-b3d1-43f1-b83a-06f5262cf265"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""ZMove"",
                    ""id"": ""3f1c8a42-4183-4a4d-a2a0-8aa9e5ce6141"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""7aa60f3f-127d-4361-a240-5f7036f4ba78"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""8875ab11-ab89-4dc8-a8f4-ede4c5986c16"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""75e011ee-1a57-4e0b-b520-a4746bfd75cb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""2f87fabc-cf73-4472-aa67-86ba7acae938"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""83a21ebd-6937-4ac3-acb6-884271d3767e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66673677-12c4-47ab-b1c9-18b5841c61f3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Cam"",
            ""id"": ""20ba848b-766a-48f0-8afb-ac6996d1822c"",
            ""actions"": [
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""d4c3c460-8f42-46ff-ada9-54b2157f9d7d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""f435f6dc-0a78-4337-8d93-58628d1c5d58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""18745c80-684d-401b-bc2b-9d87347d8e73"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""6d2e1238-fbeb-4b02-a9fa-4da0b600a3cc"",
                    ""path"": ""1DAxis(minValue=-2.5,maxValue=2.5)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7f419658-f3cc-453d-84d4-5deea606f2d7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b3937c6a-4b20-4de6-98e1-78edc0c4e426"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PControl
        m_PControl = asset.FindActionMap("PControl", throwIfNotFound: true);
        m_PControl_Move = m_PControl.FindAction("Move", throwIfNotFound: true);
        m_PControl_Interact = m_PControl.FindAction("Interact", throwIfNotFound: true);
        m_PControl_Jump = m_PControl.FindAction("Jump", throwIfNotFound: true);
        // Cam
        m_Cam = asset.FindActionMap("Cam", throwIfNotFound: true);
        m_Cam_Zoom = m_Cam.FindAction("Zoom", throwIfNotFound: true);
        m_Cam_Rotate = m_Cam.FindAction("Rotate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PControl
    private readonly InputActionMap m_PControl;
    private IPControlActions m_PControlActionsCallbackInterface;
    private readonly InputAction m_PControl_Move;
    private readonly InputAction m_PControl_Interact;
    private readonly InputAction m_PControl_Jump;
    public struct PControlActions
    {
        private @PInput m_Wrapper;
        public PControlActions(@PInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PControl_Move;
        public InputAction @Interact => m_Wrapper.m_PControl_Interact;
        public InputAction @Jump => m_Wrapper.m_PControl_Jump;
        public InputActionMap Get() { return m_Wrapper.m_PControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PControlActions set) { return set.Get(); }
        public void SetCallbacks(IPControlActions instance)
        {
            if (m_Wrapper.m_PControlActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PControlActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PControlActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PControlActionsCallbackInterface.OnMove;
                @Interact.started -= m_Wrapper.m_PControlActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PControlActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PControlActionsCallbackInterface.OnInteract;
                @Jump.started -= m_Wrapper.m_PControlActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PControlActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PControlActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_PControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public PControlActions @PControl => new PControlActions(this);

    // Cam
    private readonly InputActionMap m_Cam;
    private ICamActions m_CamActionsCallbackInterface;
    private readonly InputAction m_Cam_Zoom;
    private readonly InputAction m_Cam_Rotate;
    public struct CamActions
    {
        private @PInput m_Wrapper;
        public CamActions(@PInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Zoom => m_Wrapper.m_Cam_Zoom;
        public InputAction @Rotate => m_Wrapper.m_Cam_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_Cam; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CamActions set) { return set.Get(); }
        public void SetCallbacks(ICamActions instance)
        {
            if (m_Wrapper.m_CamActionsCallbackInterface != null)
            {
                @Zoom.started -= m_Wrapper.m_CamActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_CamActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_CamActionsCallbackInterface.OnZoom;
                @Rotate.started -= m_Wrapper.m_CamActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_CamActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_CamActionsCallbackInterface.OnRotate;
            }
            m_Wrapper.m_CamActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
            }
        }
    }
    public CamActions @Cam => new CamActions(this);
    public interface IPControlActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
    public interface ICamActions
    {
        void OnZoom(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
    }
}
